server:
  port: 6700

spring:
  application:
    name: nacos-product-provider-6700
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #数据库连接池配置
  datasource:
    username: root
    password: admin
    #假如时区报错，增加时区配置serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/nacosproduct?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #sentinel:
      #transport:
        #dashboard: localhost:8080
        #port: 8719

#整合mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mybatis/mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: com.fengye.springcloud.entities
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false

#配置控制台打印日志Debug
logging:
  level:
    com.jd.mapper: debug

#消费者将要去访问的微服务名称
server-url:
  nacos-user-service: http://nacos-product-provider
